import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine
import matplotlib.pyplot as plt
import seaborn as sns
import os
from dotenv import load_dotenv

# --- KONFIGURASI ENVIRONMENT (BARU) ---
# 1. Load Environment Variables (Baca file .env)
# Script akan mencari file .env di folder project
load_dotenv()

# Ambil kredensial dari file .env (Rahasia aman!)
DB_USER = os.getenv('DB_USER')
DB_PASS = os.getenv('DB_PASS')
DB_HOST = os.getenv('DB_HOST')
DB_PORT = os.getenv('DB_PORT')
DB_NAME = os.getenv('DB_NAME')

# 2. Setup Database Connection
print("✅ Mencoba terhubung ke Database menggunakan .env...")

# Cek apakah password terbaca (Optional: hanya untuk debug jika gagal)
if not DB_PASS:
    print("❌ ERROR: Password tidak ditemukan di file .env!")
else:
    # Format koneksi: postgresql://user:password@host:port/dbname
    db_url = f"postgresql://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
    db_engine = create_engine(db_url)
    db_connection = db_engine.connect()
    print("✅ Koneksi Sukses! Mengambil data...")

# --- MULAI ANALISIS DI BAWAH SINI ---

query = """
SELECT 
    m.medication_description as medication_name,
    SUM(m.total_cost) as total_spend
FROM mart.medications m
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10;
"""

df = pd.read_sql(query, db_connection)
print("✅ Data berhasil ditarik dari SQL!")
print(df)

plt.figure(figsize=(12, 6))
sns.barplot(data=df, x='total_spend', y='medication_name', hue='medication_name', palette='viridis', legend=False)
plt.title('Top 10 High-Cost Medications (Generated by Python)', fontsize=14, fontweight='bold')
plt.xlabel('Total Spend ($)', fontsize=12)
plt.ylabel('Medication Name', fontsize=12)
plt.grid(axis='x', linestyle='--', alpha=0.7)

output_path = 'output/visualization/python_top_medications.jpg'
plt.tight_layout()
plt.savefig(output_path)

print(f"🎉 Sukses! Grafik telah disimpan di: {output_path}")

# --- BAGIAN TAMBAHAN: STATISTIK KORELASI ---
print("\n🔍 Sedang menghitung Korelasi Umur vs Biaya...")

# Query: Ambil Umur dan Total Biaya per Pasien
# Perbaikan: Menggunakan "Id" dan "BIRTHDATE" (Huruf Besar sesuai database)
query_corr = """
SELECT 
    DATE_PART('year', AGE(p."BIRTHDATE"::DATE)) as age,
    SUM(m.total_cost) as total_medication_cost
FROM mart.medications m
JOIN raw.patients p ON m.patient_id = p."Id"
GROUP BY 1
"""

df_corr = pd.read_sql(query_corr, db_connection)

# Hitung Angka Statistik (Korelasi Pearson)
correlation = df_corr['age'].corr(df_corr['total_medication_cost'])
print(f"📊 Nilai Korelasi (r): {correlation:.2f}")

# Buat Scatter Plot
plt.figure(figsize=(10, 6))
sns.scatterplot(data=df_corr, x='age', y='total_medication_cost', alpha=0.6, color='blue')
plt.title(f'Correlation: Patient Age vs Medication Cost (r={correlation:.2f})', fontsize=14)
plt.xlabel('Age (Years)')
plt.ylabel('Total Cost ($)')
plt.grid(True, linestyle='--', alpha=0.5)

# Simpan Grafik Kedua
plt.savefig('output/visualization/python_age_cost_correlation.jpg')
print("🎉 Grafik Korelasi berhasil disimpan!")

# --- BAGIAN 3: SEGMENTASI PASIEN (4-KUADRAN) ---
print("\n🔍 Sedang menjalankan Segmentasi Pasien (High Cost & Utilizer)...")

# 1. Query Data Agregat per Pasien
query_segmentation = """
SELECT 
    p."Id" as patient_id,
    COUNT(DISTINCT e."Id") as total_encounters,
    COALESCE(SUM(m.total_cost), 0) as total_med_cost
FROM raw.patients p
LEFT JOIN raw.encounters e ON p."Id" = e."PATIENT"
LEFT JOIN mart.medications m ON p."Id" = m.patient_id
GROUP BY 1
"""

df_seg = pd.read_sql(query_segmentation, db_connection)

# 2. Tentukan Ambang Batas (Threshold)
cost_threshold = df_seg['total_med_cost'].quantile(0.75)
util_threshold = df_seg['total_encounters'].quantile(0.75)

print(f"📊 Threshold Biaya (High): > ${cost_threshold:,.2f}")
print(f"📊 Threshold Kunjungan (High): > {util_threshold} kali")

# 3. Fungsi Klasifikasi
def classify_patient(row):
    if row['total_med_cost'] >= cost_threshold and row['total_encounters'] >= util_threshold:
        return 'HighCost - HighUtil'
    elif row['total_med_cost'] >= cost_threshold and row['total_encounters'] < util_threshold:
        return 'HighCost - LowUtil'
    elif row['total_med_cost'] < cost_threshold and row['total_encounters'] >= util_threshold:
        return 'LowCost - HighUtil'
    else:
        return 'LowCost - LowUtil'

df_seg['segment'] = df_seg.apply(classify_patient, axis=1)

# 4. Visualisasi (Indentasi Sudah Diperbaiki)
plt.figure(figsize=(10, 6))
sns.countplot(
    data=df_seg, 
    x='segment', 
    hue='segment', 
    legend=False, 
    order=[
        'HighCost - HighUtil', 'HighCost - LowUtil', 
        'LowCost - HighUtil', 'LowCost - LowUtil'
    ], 
    palette='magma'
)
plt.title('Patient Segmentation: Cost vs. Utilization', fontsize=14)
plt.xlabel('Segment')
plt.ylabel('Number of Patients')
plt.grid(axis='y', linestyle='--', alpha=0.5)

plt.savefig('output/visualization/python_patient_segmentation.jpg')
print("🎉 Grafik Segmentasi berhasil disimpan!")

# 5. Tampilkan Top 5 Pasien
print("\n🚨 DAFTAR PASIEN PRIORITAS (High Cost & High Utilizer):")
high_priority = df_seg[df_seg['segment'] == 'HighCost - HighUtil'].sort_values(by='total_med_cost', ascending=False).head(5)
print(high_priority[['patient_id', 'total_encounters', 'total_med_cost']])

# --- BAGIAN 4: COST CONCENTRATION INDEX ---
print("\n💰 Menghitung Cost Concentration Index...")

# 1. Ambil data total biaya per obat
# KOREKSI: Menggunakan nama kolom yang benar 'medication_description'
query_concentration = """
SELECT 
    medication_description as description, 
    SUM(total_cost) as total_cost
FROM mart.medications
GROUP BY 1
ORDER BY 2 DESC
"""

df_conc = pd.read_sql(query_concentration, db_connection)

# 2. Hitung Total Belanja (Denominator)
total_all_spend = df_conc['total_cost'].sum()

# 3. Hitung Persentase (Share)
# Top 1 (Baris pertama)
top_1_val = df_conc.iloc[0]['total_cost']
top_1_share = (top_1_val / total_all_spend) * 100

# Top 5 (5 Baris pertama dijumlah)
top_5_val = df_conc.head(5)['total_cost'].sum()
top_5_share = (top_5_val / total_all_spend) * 100

# Top 10 (10 Baris pertama dijumlah)
top_10_val = df_conc.head(10)['total_cost'].sum()
top_10_share = (top_10_val / total_all_spend) * 100

# 4. Tampilkan Tabel Rapih di Terminal
print("\n📊 TABLE: Cost Concentration Index")
print("=" * 45)
print(f"{'Metric':<20} | {'% Share of Total Spend':<20}")
print("-" * 45)
print(f"{'Top 1 Drug':<20} | {top_1_share:.2f}%")
print(f"{'Top 5 Drugs':<20} | {top_5_share:.2f}%")
print(f"{'Top 10 Drugs':<20} | {top_10_share:.2f}%")
print("=" * 45)
print(f"(Total Spend Analyzed: ${total_all_spend:,.2f})")
