-- Auto-generated from Synthea CSV headers
CREATE SCHEMA IF NOT EXISTS raw;

CREATE TABLE IF NOT EXISTS raw."allergies" (
  "START" TEXT,
  "STOP" TEXT,
  "PATIENT" TEXT,
  "ENCOUNTER" TEXT,
  "CODE" TEXT,
  "SYSTEM" TEXT,
  "DESCRIPTION" TEXT,
  "TYPE" TEXT,
  "CATEGORY" TEXT,
  "REACTION1" TEXT,
  "DESCRIPTION1" TEXT,
  "SEVERITY1" TEXT,
  "REACTION2" TEXT,
  "DESCRIPTION2" TEXT,
  "SEVERITY2" TEXT
);

CREATE TABLE IF NOT EXISTS raw."careplans" (
  "Id" TEXT,
  "START" TEXT,
  "STOP" TEXT,
  "PATIENT" TEXT,
  "ENCOUNTER" TEXT,
  "CODE" TEXT,
  "DESCRIPTION" TEXT,
  "REASONCODE" TEXT,
  "REASONDESCRIPTION" TEXT
);

CREATE TABLE IF NOT EXISTS raw."claims" (
  "Id" TEXT,
  "PATIENTID" TEXT,
  "PROVIDERID" TEXT,
  "PRIMARYPATIENTINSURANCEID" TEXT,
  "SECONDARYPATIENTINSURANCEID" TEXT,
  "DEPARTMENTID" TEXT,
  "PATIENTDEPARTMENTID" TEXT,
  "DIAGNOSIS1" TEXT,
  "DIAGNOSIS2" TEXT,
  "DIAGNOSIS3" TEXT,
  "DIAGNOSIS4" TEXT,
  "DIAGNOSIS5" TEXT,
  "DIAGNOSIS6" TEXT,
  "DIAGNOSIS7" TEXT,
  "DIAGNOSIS8" TEXT,
  "REFERRINGPROVIDERID" TEXT,
  "APPOINTMENTID" TEXT,
  "CURRENTILLNESSDATE" TEXT,
  "SERVICEDATE" TEXT,
  "SUPERVISINGPROVIDERID" TEXT,
  "STATUS1" TEXT,
  "STATUS2" TEXT,
  "STATUSP" TEXT,
  "OUTSTANDING1" TEXT,
  "OUTSTANDING2" TEXT,
  "OUTSTANDINGP" TEXT,
  "LASTBILLEDDATE1" TEXT,
  "LASTBILLEDDATE2" TEXT,
  "LASTBILLEDDATEP" TEXT,
  "HEALTHCARECLAIMTYPEID1" TEXT,
  "HEALTHCARECLAIMTYPEID2" TEXT
);

CREATE TABLE IF NOT EXISTS raw."claims_transactions" (
  "ID" TEXT,
  "CLAIMID" TEXT,
  "CHARGEID" TEXT,
  "PATIENTID" TEXT,
  "TYPE" TEXT,
  "AMOUNT" TEXT,
  "METHOD" TEXT,
  "FROMDATE" TEXT,
  "TODATE" TEXT,
  "PLACEOFSERVICE" TEXT,
  "PROCEDURECODE" TEXT,
  "MODIFIER1" TEXT,
  "MODIFIER2" TEXT,
  "DIAGNOSISREF1" TEXT,
  "DIAGNOSISREF2" TEXT,
  "DIAGNOSISREF3" TEXT,
  "DIAGNOSISREF4" TEXT,
  "UNITS" TEXT,
  "DEPARTMENTID" TEXT,
  "NOTES" TEXT,
  "UNITAMOUNT" TEXT,
  "TRANSFEROUTID" TEXT,
  "TRANSFERTYPE" TEXT,
  "PAYMENTS" TEXT,
  "ADJUSTMENTS" TEXT,
  "TRANSFERS" TEXT,
  "OUTSTANDING" TEXT,
  "APPOINTMENTID" TEXT,
  "LINENOTE" TEXT,
  "PATIENTINSURANCEID" TEXT,
  "FEESCHEDULEID" TEXT,
  "PROVIDERID" TEXT,
  "SUPERVISINGPROVIDERID" TEXT
);

CREATE TABLE IF NOT EXISTS raw."conditions" (
  "START" TEXT,
  "STOP" TEXT,
  "PATIENT" TEXT,
  "ENCOUNTER" TEXT,
  "SYSTEM" TEXT,
  "CODE" TEXT,
  "DESCRIPTION" TEXT
);

CREATE TABLE IF NOT EXISTS raw."devices" (
  "START" TEXT,
  "STOP" TEXT,
  "PATIENT" TEXT,
  "ENCOUNTER" TEXT,
  "CODE" TEXT,
  "DESCRIPTION" TEXT,
  "UDI" TEXT
);

CREATE TABLE IF NOT EXISTS raw."encounters" (
  "Id" TEXT,
  "START" TEXT,
  "STOP" TEXT,
  "PATIENT" TEXT,
  "ORGANIZATION" TEXT,
  "PROVIDER" TEXT,
  "PAYER" TEXT,
  "ENCOUNTERCLASS" TEXT,
  "CODE" TEXT,
  "DESCRIPTION" TEXT,
  "BASE_ENCOUNTER_COST" TEXT,
  "TOTAL_CLAIM_COST" TEXT,
  "PAYER_COVERAGE" TEXT,
  "REASONCODE" TEXT,
  "REASONDESCRIPTION" TEXT
);

CREATE TABLE IF NOT EXISTS raw."imaging_studies" (
  "Id" TEXT,
  "DATE" TEXT,
  "PATIENT" TEXT,
  "ENCOUNTER" TEXT,
  "SERIES_UID" TEXT,
  "BODYSITE_CODE" TEXT,
  "BODYSITE_DESCRIPTION" TEXT,
  "MODALITY_CODE" TEXT,
  "MODALITY_DESCRIPTION" TEXT,
  "INSTANCE_UID" TEXT,
  "SOP_CODE" TEXT,
  "SOP_DESCRIPTION" TEXT,
  "PROCEDURE_CODE" TEXT
);

CREATE TABLE IF NOT EXISTS raw."immunizations" (
  "DATE" TEXT,
  "PATIENT" TEXT,
  "ENCOUNTER" TEXT,
  "CODE" TEXT,
  "DESCRIPTION" TEXT,
  "BASE_COST" TEXT
);

CREATE TABLE IF NOT EXISTS raw."medications" (
  "START" TEXT,
  "STOP" TEXT,
  "PATIENT" TEXT,
  "PAYER" TEXT,
  "ENCOUNTER" TEXT,
  "CODE" TEXT,
  "DESCRIPTION" TEXT,
  "BASE_COST" TEXT,
  "PAYER_COVERAGE" TEXT,
  "DISPENSES" TEXT,
  "TOTALCOST" TEXT,
  "REASONCODE" TEXT,
  "REASONDESCRIPTION" TEXT
);

CREATE TABLE IF NOT EXISTS raw."observations" (
  "DATE" TEXT,
  "PATIENT" TEXT,
  "ENCOUNTER" TEXT,
  "CATEGORY" TEXT,
  "CODE" TEXT,
  "DESCRIPTION" TEXT,
  "VALUE" TEXT,
  "UNITS" TEXT,
  "TYPE" TEXT
);

CREATE TABLE IF NOT EXISTS raw."organizations" (
  "Id" TEXT,
  "NAME" TEXT,
  "ADDRESS" TEXT,
  "CITY" TEXT,
  "STATE" TEXT,
  "ZIP" TEXT,
  "LAT" TEXT,
  "LON" TEXT,
  "PHONE" TEXT,
  "REVENUE" TEXT,
  "UTILIZATION" TEXT
);

CREATE TABLE IF NOT EXISTS raw."patients" (
  "Id" TEXT,
  "BIRTHDATE" TEXT,
  "DEATHDATE" TEXT,
  "SSN" TEXT,
  "DRIVERS" TEXT,
  "PASSPORT" TEXT,
  "PREFIX" TEXT,
  "FIRST" TEXT,
  "MIDDLE" TEXT,
  "LAST" TEXT,
  "SUFFIX" TEXT,
  "MAIDEN" TEXT,
  "MARITAL" TEXT,
  "RACE" TEXT,
  "ETHNICITY" TEXT,
  "GENDER" TEXT,
  "BIRTHPLACE" TEXT,
  "ADDRESS" TEXT,
  "CITY" TEXT,
  "STATE" TEXT,
  "COUNTY" TEXT,
  "FIPS" TEXT,
  "ZIP" TEXT,
  "LAT" TEXT,
  "LON" TEXT,
  "HEALTHCARE_EXPENSES" TEXT,
  "HEALTHCARE_COVERAGE" TEXT,
  "INCOME" TEXT
);

CREATE TABLE IF NOT EXISTS raw."payer_transitions" (
  "PATIENT" TEXT,
  "MEMBERID" TEXT,
  "START_DATE" TEXT,
  "END_DATE" TEXT,
  "PAYER" TEXT,
  "SECONDARY_PAYER" TEXT,
  "PLAN_OWNERSHIP" TEXT,
  "OWNER_NAME" TEXT
);

CREATE TABLE IF NOT EXISTS raw."payers" (
  "Id" TEXT,
  "NAME" TEXT,
  "OWNERSHIP" TEXT,
  "ADDRESS" TEXT,
  "CITY" TEXT,
  "STATE_HEADQUARTERED" TEXT,
  "ZIP" TEXT,
  "PHONE" TEXT,
  "AMOUNT_COVERED" TEXT,
  "AMOUNT_UNCOVERED" TEXT,
  "REVENUE" TEXT,
  "COVERED_ENCOUNTERS" TEXT,
  "UNCOVERED_ENCOUNTERS" TEXT,
  "COVERED_MEDICATIONS" TEXT,
  "UNCOVERED_MEDICATIONS" TEXT,
  "COVERED_PROCEDURES" TEXT,
  "UNCOVERED_PROCEDURES" TEXT,
  "COVERED_IMMUNIZATIONS" TEXT,
  "UNCOVERED_IMMUNIZATIONS" TEXT,
  "UNIQUE_CUSTOMERS" TEXT,
  "QOLS_AVG" TEXT,
  "MEMBER_MONTHS" TEXT
);

CREATE TABLE IF NOT EXISTS raw."procedures" (
  "START" TEXT,
  "STOP" TEXT,
  "PATIENT" TEXT,
  "ENCOUNTER" TEXT,
  "SYSTEM" TEXT,
  "CODE" TEXT,
  "DESCRIPTION" TEXT,
  "BASE_COST" TEXT,
  "REASONCODE" TEXT,
  "REASONDESCRIPTION" TEXT
);

CREATE TABLE IF NOT EXISTS raw."providers" (
  "Id" TEXT,
  "ORGANIZATION" TEXT,
  "NAME" TEXT,
  "GENDER" TEXT,
  "SPECIALITY" TEXT,
  "ADDRESS" TEXT,
  "CITY" TEXT,
  "STATE" TEXT,
  "ZIP" TEXT,
  "LAT" TEXT,
  "LON" TEXT,
  "ENCOUNTERS" TEXT,
  "PROCEDURES" TEXT
);

CREATE TABLE IF NOT EXISTS raw."supplies" (
  "DATE" TEXT,
  "PATIENT" TEXT,
  "ENCOUNTER" TEXT,
  "CODE" TEXT,
  "DESCRIPTION" TEXT,
  "QUANTITY" TEXT
);
